# 初回のみ実行: Unityライセンスを取得するワークフロー
# .github/workflows/activation.yml

name: Acquire Unity License

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.10f1  # 使用するUnityバージョン

      - name: Upload manual activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

# 実行手順:
# 1. GitHubリポジトリの「Actions」タブから「Acquire Unity License」を実行
# 2. 完了後、アーティファクトから .alf ファイルをダウンロード
# 3. https://license.unity3d.com/manual にアクセスし、.alf ファイルをアップロード
# 4. ダウンロードした .ulf ファイルの内容をコピー
# 5. リポジトリの Settings → Secrets に以下を追加:
#    - UNITY_LICENSE: .ulfファイルの内容全体
#    - UNITY_EMAIL: Unityアカウントのメールアドレス
#    - UNITY_PASSWORD: Unityアカウントのパスワード
